"""
Explore feed — variable-reward cards generated by Sonnet, cached per day.
"""
import json
from datetime import date
from fastapi import APIRouter, Depends, HTTPException
from auth import verify_token
from db.helpers import get_db
from db.schema import ExploreCache, Curriculum, User
from chatbot.router import stream_anthropic

router = APIRouter()

EXPLORE_SUBTYPES = ["real_story", "hot_take", "connection", "did_you_know", "what_would_you_do"]

EXPLORE_SYSTEM = """You are generating variable-reward "Explore" cards for a learner.
These are NOT lessons. They are engaging, surprising, scroll-stopping mini-stories.
Think: the best tweet or Reddit post about this topic — not a textbook paragraph.
Rules:
- No bullet points. Short paragraphs only.
- First-person narrative where possible ("I once met a researcher who...")
- Each card must end with a hook or open question.
- Keep each card under 120 words.
- Vary subtypes: real_story, hot_take, connection, did_you_know, what_would_you_do
Return JSON array of 10 cards."""


@router.get("/{user_id}")
def get_explore(user_id: str, claims: dict = Depends(verify_token)):
    today = date.today()
    with get_db() as db:
        cached = (
            db.query(ExploreCache)
            .filter(ExploreCache.user_id == user_id, ExploreCache.cache_date == today)
            .first()
        )
        if cached:
            return {"cards": cached.cards_json}

        # Get active curriculum topic
        curriculum = (
            db.query(Curriculum)
            .filter(Curriculum.user_id == user_id, Curriculum.status == "active")
            .first()
        )
        topic = curriculum.topic if curriculum else "general knowledge"

    messages = [
        {
            "role": "user",
            "content": f"""Generate 10 explore cards for someone learning: {topic}

Return JSON array:
[{{"subtype": "real_story|hot_take|connection|did_you_know|what_would_you_do", "title": "...", "body": "...", "source": "optional source or empty string"}}]

JSON only, no markdown.""",
        }
    ]

    # Generate synchronously (explore is background, not streamed to user)
    full_text = ""
    for chunk in stream_anthropic("explore_cards", EXPLORE_SYSTEM, messages, max_tokens=2048):
        full_text += chunk

    try:
        cards = json.loads(full_text)
    except json.JSONDecodeError:
        cards = []

    with get_db() as db:
        db.add(ExploreCache(user_id=user_id, cache_date=today, cards_json=cards))

    return {"cards": cards}
